# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for Aligo SMS MCP Server
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install --production --ignore-scripts

# Copy application source code
COPY . .

# Default command to run the MCP server
CMD ["node", "index.js"]
